version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pedbox_db
    environment:
      POSTGRES_USER: pedbox_user
      POSTGRES_PASSWORD: pedbox_password
      POSTGRES_DB: pedbox_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: